services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"  # Mapea el puerto 3306 del contenedor al puerto 3307 de la máquina host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

