server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/log/*.log

  - job_name: flask-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask-app
          __path__: /var/log/flask-app/*.log
          # Asegúrate de que Flask app log en un volumen montado que Promtail pueda acceder
